<%
Checking "0|1"
'Dim Name, CarrierCode
if CountTableValues >= 0 then 
	CreatedDate = ConvertDate(aTableValues(1, 0),2)
    CreatedTime = aTableValues(2, 0)
	Expired = aTableValues(3, 0)
	Name = aTableValues(4, 0)
	CarrierCode = aTableValues(5, 0)
	Countries = aTableValues(152, 0)
	OtherChargesPrintType = aTableValues(159, 0)
	ComisionRate = aTableValues(160, 0)
end if
%>
<HTML>
<HEAD><TITLE>AWB - Aimar - Administración</TITLE>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<SCRIPT language="javascript" src="img/matchvalues.js"></SCRIPT>
<SCRIPT language="javascript" src="img/vals.js"></SCRIPT>
<SCRIPT LANGUAGE="JavaScript">
	function validar(Action) {
  		if (Action != 3) {
			if (!valSelec(document.forma.Countries)){return (false)};		
			if (!valTxt(document.forma.Name, 3, 5)){return (false)};
			if (!valTxt(document.forma.CarrierCode, 2, 5)){return (false)};
		}
	    document.forma.Action.value = Action;
		document.forma.submit();			 
	 }
</SCRIPT>
<LINK REL="stylesheet" TYPE="text/css" HREF="img/estilos.css">
<BODY text=#000000 vLink=#000000 aLink=#000000 link=#000000 bgColor=#ffffff leftMargin=0 topMargin=0 marginheight="0" marginwidth="0">
	<TABLE cellspacing=0 cellpadding=2 width=400 align=center>
	<FORM name="forma" action="InsertData.asp" method="post">
	<INPUT name="Action" type=hidden value=0>
	<INPUT name="GID" type=hidden value="<%=GroupID%>">
	<INPUT name="OID" type=hidden value="<%=ObjectID%>">
	<INPUT name="CD" type=hidden value="<%=CreatedDate%>">
	<INPUT name="CT" type=hidden value="<%=CreatedTime%>">
		<TR><TD class=label align=right width="175"><b>Código:</b></TD><TD class=label align=left colspan=2><%if ObjectID <> 0 then response.write ObjectID End if%></TD></TR> 
		<TR><TD class=label align=right><b>Fecha Creación:</b></TD><TD class=label align=left colspan=2><%=CreatedDate%></TD></TR> 
        <TR><TD class=label align=right><b>Activa:</b></TD><TD class=label align=left colspan=2><INPUT name=Expired TYPE=checkbox class=label <%If Expired = False Then response.write " checked"  End If%>></TD></TR>
		<TR><TD class=label align=right><b>Pais:</b></TD><TD class=label align=left colspan=2>
			<select name="Countries" id="Pais" class="label">
				<option value="-1">Seleccionar</option>
				<%DisplayCountries (Countries)%>
			</select>	
		</TD></TR>
		<TR><TD class=label align=right><b>Nombre:</b></TD><TD class=label align=left colspan=2><INPUT TYPE=text class=label name="Name" id="Nombre Transportista" value="<%=Name%>" maxlength="45"></TD></TR> 
        <TR><TD class=label align=right><b>Código Transportista:</b></TD><TD class=label align=left colspan=2><INPUT TYPE=text class=label name="CarrierCode" id="Código Transportista" value="<%=CarrierCode%>" maxlength="5"></TD></TR>
        <TR><TD class=label align=right><b>Tasa Comision:</b></TD><TD class=label align=left colspan=2><INPUT TYPE=text class=label name="ComisionRate" id="Tasa Comision" value="<%=ComisionRate%>" maxlength="5" onKeyUp="res(this,numb);"></TD></TR>
		<TR><TD class=label align=right><b>Forma Impresion Cuadro de Otros Cargos:</b></TD><TD class=label align=left colspan=2>
			<select name="OtherChargesPrintType" id="Forma Impresion Cuadro de Otros Cargos" class="label">
				<option value="0">Vertical (default)</option>
				<option value="1">Horizontal</option>
			</select>	
		</TD></TR>		
		<%if CountTableValues > 0 then%>
				  <TR>
					 <TD class=label align=right><b>Formato de Plantilla:</b></TD>
					 <TD class=label align=center>Horizontal</TD>
					 <TD class=label align=center>Vertical</TD>
   				  </TR>
					<TR><TD class=label align=right>Cod.Aeropuerto Salida</TD><TD class=label align=center><input type=text class=label name="ver_AirportCode" id="Cod.Aeropuerto Salida vertical" value="<%=aTableValues(142,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AirportCode" id="Cod.Aeropuerto Salida horizontal" value="<%=aTableValues(143,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>No. de AWB</TD><TD class=label align=center><input type=text class=label name="ver_AWBNumber" id="No. de AWB vertical" value="<%=aTableValues(6,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AWBNumber" id="No. de AWB horizontal" value="<%=aTableValues(7,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>No. de AWB (2)</TD><TD class=label align=center><input type=text class=label name="ver_AWBNumber2" id="No. de AWB vertical (2)" value="<%=aTableValues(161,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AWBNumber2" id="No. de AWB horizontal (2)" value="<%=aTableValues(162,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>No. de AWB (3)</TD><TD class=label align=center><input type=text class=label name="ver_AWBNumber3" id="No. de AWB vertical (3)" value="<%=aTableValues(163,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AWBNumber3" id="No. de AWB horizontal (3)" value="<%=aTableValues(164,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>No. Cuenta Embarcador</TD><TD class=label align=center><input type=text class=label name="ver_AccountShipperNo" id="No. Cuenta Embarcador vertical" value="<%=aTableValues(8,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AccountShipperNo" id="No. Cuenta Embarcador horizontal" value="<%=aTableValues(9,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Datos Embarcador</TD><TD class=label align=center><input type=text class=label name="ver_ShipperData" id="Datos Embarcador vertical" value="<%=aTableValues(10,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_ShipperData" id="Datos Embarcador horizontal" value="<%=aTableValues(11,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>No. Cuenta Destinatario</TD><TD class=label align=center><input type=text class=label name="ver_AccountConsignerNo" id="No. Cuenta Destinatario vertical" value="<%=aTableValues(12,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AccountConsignerNo" id="No. Cuenta Destinatario horizontal" value="<%=aTableValues(13,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Datos Destinatario</TD><TD class=label align=center><input type=text class=label name="ver_ConsignerData" id="Datos Destinatario vertical" value="<%=aTableValues(14,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_ConsignerData" id="Datos Destinatario horizontal" value="<%=aTableValues(15,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Datos Agente</TD><TD class=label align=center><input type=text class=label name="ver_AgentData" id="Datos Agente vertical" value="<%=aTableValues(16,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AgentData" id="Datos Agente horizontal" value="<%=aTableValues(17,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Informacion Contable</TD><TD class=label align=center><input type=text class=label name="ver_AccountInformation" id="Informacion Contable vertical" value="<%=aTableValues(18,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AccountInformation" id="Informacion Contable horizontal" value="<%=aTableValues(19,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Codigo IATA de Agente</TD><TD class=label align=center><input type=text class=label name="ver_IATANo" id="Codigo IATA de Agente vertical" value="<%=aTableValues(20,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_IATANo" id="Codigo IATA de Agente horizontal" value="<%=aTableValues(21,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>No. Cuenta Agente</TD><TD class=label align=center><input type=text class=label name="ver_AccountAgentNo" id="No. Cuenta Agente vertical" value="<%=aTableValues(22,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AccountAgentNo" id="No. Cuenta Agente horizontal" value="<%=aTableValues(23,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Aeropuerto Salida</TD><TD class=label align=center><input type=text class=label name="ver_AirportDepID" id="Aeropuerto Salida vertical" value="<%=aTableValues(24,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AirportDepID" id="Aeropuerto Salida horizontal" value="<%=aTableValues(25,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Ruta Solicitada</TD><TD class=label align=center><input type=text class=label name="ver_RequestedRouting" id="Ruta Solicitada vertical" value="<%=aTableValues(26,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_RequestedRouting" id="Ruta Solicitada horizontal" value="<%=aTableValues(27,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Codigo Aeropuerto 1</TD><TD class=label align=center><input type=text class=label name="ver_AirportToCode1" id="Codigo Aeropuerto 1 vertical" value="<%=aTableValues(28,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AirportToCode1" id="Codigo Aeropuerto 1 horizontal" value="<%=aTableValues(29,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Transportista 1</TD><TD class=label align=center><input type=text class=label name="ver_CarrierID" id="Transportista 1 vertical" value="<%=aTableValues(30,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_CarrierID" id="Transportista 1 horizontal" value="<%=aTableValues(31,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Codigo Aeropuerto 2</TD><TD class=label align=center><input type=text class=label name="ver_AirportToCode2" id="Codigo Aeropuerto 2 vertical" value="<%=aTableValues(32,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AirportToCode2" id="Codigo Aeropuerto 2 horizontal" value="<%=aTableValues(33,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Codigo Aeropuerto 3</TD><TD class=label align=center><input type=text class=label name="ver_AirportToCode3" id="Codigo Aeropuerto 3 vertical" value="<%=aTableValues(34,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AirportToCode3" id="Codigo Aeropuerto 3 horizontal" value="<%=aTableValues(35,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Transportista 2</TD><TD class=label align=center><input type=text class=label name="ver_CarrierCode2" id="Transportista 2 vertical" value="<%=aTableValues(36,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_CarrierCode2" id="Transportista 2 horizontal" value="<%=aTableValues(37,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Transportista 3</TD><TD class=label align=center><input type=text class=label name="ver_CarrierCode3" id="Transportista 3 vertical" value="<%=aTableValues(38,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_CarrierCode3" id="Transportista 3 horizontal" value="<%=aTableValues(39,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Moneda</TD><TD class=label align=center><input type=text class=label name="ver_CurrencyID" id="Moneda vertical" value="<%=aTableValues(40,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_CurrencyID" id="Moneda horizontal" value="<%=aTableValues(41,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Codigo Cargos PP</TD><TD class=label align=center><input type=text class=label name="ver_ChargeType" id="Codigo Cargos PP vertical" value="<%=aTableValues(42,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_ChargeType" id="Codigo Cargos PP horizontal" value="<%=aTableValues(43,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargos por Peso PP</TD><TD class=label align=center><input type=text class=label name="ver_ValChargeType" id="Cargos por Peso PP vertical" value="<%=aTableValues(44,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_ValChargeType" id="Cargos por Peso PP horizontal" value="<%=aTableValues(45,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Otros Cargos PP</TD><TD class=label align=center><input type=text class=label name="ver_OtherChargeType" id="Otros Cargos PP vertical" value="<%=aTableValues(46,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_OtherChargeType" id="Otros Cargos PP horizontal" value="<%=aTableValues(47,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Codigo Cargos CC</TD><TD class=label align=center><input type=text class=label name="ver_ChargeType2" id="Codigo Cargos CC vertical" value="<%=aTableValues(153,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_ChargeType2" id="Codigo Cargos CC horizontal" value="<%=aTableValues(154,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargos por Peso CC</TD><TD class=label align=center><input type=text class=label name="ver_ValChargeType2" id="Cargos por Peso CC vertical" value="<%=aTableValues(155,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_ValChargeType2" id="Cargos por Peso CC horizontal" value="<%=aTableValues(156,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Otros Cargos CC</TD><TD class=label align=center><input type=text class=label name="ver_OtherChargeType2" id="Otros Cargos CC vertical" value="<%=aTableValues(157,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_OtherChargeType2" id="Otros Cargos CC horizontal" value="<%=aTableValues(158,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Valor Declarado Transporte</TD><TD class=label align=center><input type=text class=label name="ver_DeclaredValue" id="Valor Declarado Transporte vertical" value="<%=aTableValues(48,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_DeclaredValue" id="Valor Declarado Transporte horizontal" value="<%=aTableValues(49,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Valor Declarado Aduana</TD><TD class=label align=center><input type=text class=label name="ver_AduanaValue" id="Valor Declarado Aduana vertical" value="<%=aTableValues(50,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AduanaValue" id="Valor Declarado Aduana horizontal" value="<%=aTableValues(51,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Aeropuerto Destino</TD><TD class=label align=center><input type=text class=label name="ver_AirportDesID" id="Aeropuerto Destino vertical" value="<%=aTableValues(52,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AirportDesID" id="Aeropuerto Destino horizontal" value="<%=aTableValues(53,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Fecha Vuelo 1</TD><TD class=label align=center><input type=text class=label name="ver_FlightDate1" id="Fecha Vuelo 1 vertical" value="<%=aTableValues(54,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_FlightDate1" id="Fecha Vuelo 1 horizontal" value="<%=aTableValues(55,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Fecha Vuelo 2</TD><TD class=label align=center><input type=text class=label name="ver_FlightDate2" id="Fecha Vuelo 2 vertical" value="<%=aTableValues(56,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_FlightDate2" id="Fecha Vuelo 2 horizontal" value="<%=aTableValues(57,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Valor Asegurado</TD><TD class=label align=center><input type=text class=label name="ver_SecuredValue" id="Valor Asegurado vertical" value="<%=aTableValues(58,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_SecuredValue" id="Valor Asegurado horizontal" value="<%=aTableValues(59,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Informacion de Manejo</TD><TD class=label align=center><input type=text class=label name="ver_HandlingInformation" id="Informacion de Manejo vertical" value="<%=aTableValues(60,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_HandlingInformation" id="Informacion de Manejo horizontal" value="<%=aTableValues(61,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Observaciones</TD><TD class=label align=center><input type=text class=label name="ver_Observations" id="Observaciones vertical" value="<%=aTableValues(62,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_Observations" id="Observaciones horizontal" value="<%=aTableValues(63,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>No. Bultos</TD><TD class=label align=center><input type=text class=label name="ver_NoOfPieces" id="No. Bultos vertical" value="<%=aTableValues(64,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_NoOfPieces" id="No. Bultos horizontal" value="<%=aTableValues(65,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Peso Bruto</TD><TD class=label align=center><input type=text class=label name="ver_Weights" id="Peso Bruto vertical" value="<%=aTableValues(66,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_Weights" id="Peso Bruto horizontal" value="<%=aTableValues(67,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>kg / lb</TD><TD class=label align=center><input type=text class=label name="ver_WeightsSymbol" id="kg / lb vertical" value="<%=aTableValues(68,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_WeightsSymbol" id="kg / lb horizontal" value="<%=aTableValues(69,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Codigo Commodity</TD><TD class=label align=center><input type=text class=label name="ver_Commodities" id="Codigo Commodity vertical" value="<%=aTableValues(70,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_Commodities" id="Codigo Commodity horizontal" value="<%=aTableValues(71,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Peso a Cobrar</TD><TD class=label align=center><input type=text class=label name="ver_ChargeableWeights" id="Peso a Cobrar vertical" value="<%=aTableValues(72,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_ChargeableWeights" id="Peso a Cobrar horizontal" value="<%=aTableValues(73,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Tarifa / Cargo</TD><TD class=label align=center><input type=text class=label name="ver_CarrierRates" id="Tarifa / Cargo vertical" value="<%=aTableValues(74,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_CarrierRates" id="Tarifa / Cargo horizontal" value="<%=aTableValues(75,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Total</TD><TD class=label align=center><input type=text class=label name="ver_CarrierSubTot" id="Total vertical" value="<%=aTableValues(76,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_CarrierSubTot" id="Total horizontal" value="<%=aTableValues(77,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Naturaleza Mercancia</TD><TD class=label align=center><input type=text class=label name="ver_NatureQtyGoods" id="Naturaleza Mercancia vertical" value="<%=aTableValues(78,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_NatureQtyGoods" id="Naturaleza Mercancia horizontal" value="<%=aTableValues(79,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>No. Bultos</TD><TD class=label align=center><input type=text class=label name="ver_TotNoOfPieces" id="No. Bultos vertical" value="<%=aTableValues(80,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotNoOfPieces" id="No. Bultos horizontal" value="<%=aTableValues(81,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Peso Bruto</TD><TD class=label align=center><input type=text class=label name="ver_TotWeight" id="Peso Bruto vertical" value="<%=aTableValues(82,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotWeight" id="Peso Bruto horizontal" value="<%=aTableValues(83,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Tarifas</TD><TD class=label align=center><input type=text class=label name="ver_TotCarrierRate" id="Tarifas vertical" value="<%=aTableValues(84,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotCarrierRate" id="Tarifas horizontal" value="<%=aTableValues(85,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargo Peso PP</TD><TD class=label align=center><input type=text class=label name="ver_TotChargeWeightPrepaid" id="Cargo Peso PP vertical" value="<%=aTableValues(86,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotChargeWeightPrepaid" id="Cargo Peso PP horizontal" value="<%=aTableValues(87,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargo Peso CC</TD><TD class=label align=center><input type=text class=label name="ver_TotChargeWeightCollect" id="Cargo Peso CC vertical" value="<%=aTableValues(88,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotChargeWeightCollect" id="Cargo Peso CC horizontal" value="<%=aTableValues(89,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargo Valor PP</TD><TD class=label align=center><input type=text class=label name="ver_TotChargeValuePrepaid" id="Cargo Valor PP vertical" value="<%=aTableValues(90,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotChargeValuePrepaid" id="Cargo Valor PP horizontal" value="<%=aTableValues(91,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargo Valor CC</TD><TD class=label align=center><input type=text class=label name="ver_TotChargeValueCollect" id="Cargo Valor CC vertical" value="<%=aTableValues(92,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotChargeValueCollect" id="Cargo Valor CC horizontal" value="<%=aTableValues(93,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Impuesto PP</TD><TD class=label align=center><input type=text class=label name="ver_TotChargeTaxPrepaid" id="Impuesto PP vertical" value="<%=aTableValues(94,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotChargeTaxPrepaid" id="Impuesto PP horizontal" value="<%=aTableValues(95,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Impuesto CC</TD><TD class=label align=center><input type=text class=label name="ver_TotChargeTaxCollect" id="Impuesto CC vertical" value="<%=aTableValues(96,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotChargeTaxCollect" id="Impuesto CC horizontal" value="<%=aTableValues(97,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargos Agente PP</TD><TD class=label align=center><input type=text class=label name="ver_AnotherChargesAgentPrepaid" id="Cargos Agente PP vertical" value="<%=aTableValues(98,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AnotherChargesAgentPrepaid" id="Cargos Agente PP horizontal" value="<%=aTableValues(99,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargos Agente CC</TD><TD class=label align=center><input type=text class=label name="ver_AnotherChargesAgentCollect" id="Cargos Agente CC vertical" value="<%=aTableValues(100,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AnotherChargesAgentCollect" id="Cargos Agente CC horizontal" value="<%=aTableValues(101,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargos Transportista PP</TD><TD class=label align=center><input type=text class=label name="ver_AnotherChargesCarrierPrepaid" id="Cargos Transportista PP vertical" value="<%=aTableValues(102,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AnotherChargesCarrierPrepaid" id="Cargos Transportista PP horizontal" value="<%=aTableValues(103,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Cargos Transportista CC</TD><TD class=label align=center><input type=text class=label name="ver_AnotherChargesCarrierCollect" id="Cargos Transportista CC vertical" value="<%=aTableValues(104,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AnotherChargesCarrierCollect" id="Cargos Transportista CC horizontal" value="<%=aTableValues(105,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Total PP</TD><TD class=label align=center><input type=text class=label name="ver_TotPrepaid" id="Total PP vertical" value="<%=aTableValues(106,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotPrepaid" id="Total PP horizontal" value="<%=aTableValues(107,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Total CC</TD><TD class=label align=center><input type=text class=label name="ver_TotCollect" id="Total CC vertical" value="<%=aTableValues(108,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TotCollect" id="Total CC horizontal" value="<%=aTableValues(109,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Otros Cargos</TD><TD class=label align=center><input type=text class=label name="ver_TerminalFee" id="Terminal Fee vertical" value="<%=aTableValues(110,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_TerminalFee" id="Terminal Fee horizontal" value="<%=aTableValues(111,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Factura</TD><TD class=label align=center><input type=text class=label name="ver_Invoice" id="Factura vertical" value="<%=aTableValues(130,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_Invoice" id="Factura horizontal" value="<%=aTableValues(131,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Licencia Exportacion</TD><TD class=label align=center><input type=text class=label name="ver_ExportLic" id="Licencia Exportacion vertical" value="<%=aTableValues(132,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_ExportLic" id="Licencia Exportacion horizontal" value="<%=aTableValues(133,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Firma Contacto Agente</TD><TD class=label align=center><input type=text class=label name="ver_AgentContactSignature" id="Firma Contacto Agente vertical" value="<%=aTableValues(134,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AgentContactSignature" id="Firma Contacto Agente horizontal" value="<%=aTableValues(135,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Instrucciones</TD><TD class=label align=center><input type=text class=label name="ver_Instructions" id="Instrucciones vertical" value="<%=aTableValues(136,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_Instructions" id="Instrucciones horizontal" value="<%=aTableValues(137,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Firma Agente</TD><TD class=label align=center><input type=text class=label name="ver_AgentSignature" id="Firma Agente vertical" value="<%=aTableValues(138,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AgentSignature" id="Firma Agente horizontal" value="<%=aTableValues(139,0)%>" maxlength="5"></TD></TR>
					<TR><TD class=label align=right>Fecha AWB</TD><TD class=label align=center><input type=text class=label name="ver_AWBDate" id="Fecha AWB vertical" value="<%=aTableValues(140,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_AWBDate" id="Fecha AWB horizontal" value="<%=aTableValues(141,0)%>" maxlength="5"></TD></TR>
                    <TR><TD class=label align=right>Notify To</TD><TD class=label align=center><input type=text class=label name="ver_id_cliente_order" id="Notify vertical" value="<%=aTableValues(165,0)%>" maxlength="5"></TD><TD class=label align=center><input type=text class=label name="hor_id_cliente_order" id="Notify horizontal" value="<%=aTableValues(166,0)%>" maxlength="5"></TD></TR>
		<%end if%>
		<TR>
		<TD colspan="3" class=label align=center>
			<TABLE cellspacing=0 cellpadding=2 width=200>
				  <TR>
							<%if CountTableValues = -1 then%>
									 <TD class=label align=center colspan=2><INPUT name=enviar type=button onClick="JavaScript:validar(4)" value="&nbsp;&nbsp;Agregar&nbsp;&nbsp;" class=label></TD>
							<%else%>
									 <TD class=label align=center colspan=2><INPUT name=enviar type=button onClick="Javascript:window.open('AWBPrint.asp?Action=5&CID=<%=ObjectID%>','AWBPrint','menubar=1,resizable=1,scrollbars=1,toolbar=1');return false;" value="&nbsp;&nbsp;Previsualizar Plantilla&nbsp;&nbsp;" class=label></TD>
									 <TD class=label align=center colspan=2><INPUT name=enviar type=button onClick="JavaScript:validar(2)" value="&nbsp;&nbsp;Actualizar&nbsp;&nbsp;" class=label></TD>
									 <!--<TD class=label align=center colspan=2><INPUT name=enviar type=button onClick="JavaScript:validar(3)" value="&nbsp;&nbsp;Eliminar&nbsp;&nbsp;" class=label></TD>-->
							<%end if%>
					</TR>
			</TABLE>
		<TD>
		</TR>
	</FORM>
	</TABLE>
<script>
selecciona('forma.OtherChargesPrintType','<%=OtherChargesPrintType%>');
</script>	
</BODY>
</HTML>